"""initial

Revision ID: 47ef6902e297
Revises: 
Create Date: 2026-05-05 20:42:18.882631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ef6902e297'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_actions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('agent_actions', 'approval_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index(op.f('idx_agent_actions_approval'), table_name='agent_actions')
    op.drop_index(op.f('idx_agent_actions_user_ts'), table_name='agent_actions')
    op.drop_constraint(op.f('agent_actions_user_id_fkey'), 'agent_actions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_actions', 'users', ['user_id'], ['id'])
    op.alter_column('agent_suggestions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('agent_suggestions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'new'::text"))
    op.drop_index(op.f('idx_agent_suggestions_status'), table_name='agent_suggestions')
    op.drop_index(op.f('idx_agent_suggestions_user_ts'), table_name='agent_suggestions')
    op.drop_constraint(op.f('agent_suggestions_user_id_fkey'), 'agent_suggestions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_suggestions', 'users', ['user_id'], ['id'])
    op.alter_column('audit_log', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('audit_log', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'info'::text"))
    op.drop_index(op.f('idx_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_session_ts'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_user_ts'), table_name='audit_log')
    op.drop_constraint(op.f('audit_log_session_id_fkey'), 'audit_log', type_='foreignkey')
    op.drop_constraint(op.f('audit_log_user_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'audit_log', 'users', ['user_id'], ['id'])
    op.alter_column('chat_messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.drop_index(op.f('idx_chat_messages_user_ts'), table_name='chat_messages')
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_session_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.alter_column('memory_feedback', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_constraint(op.f('memory_feedback_memory_item_id_fkey'), 'memory_feedback', type_='foreignkey')
    op.drop_constraint(op.f('memory_feedback_user_id_fkey'), 'memory_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'memory_feedback', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'memory_feedback', 'memory_items', ['memory_item_id'], ['id'])
    op.alter_column('memory_items', 'kind',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('memory_items', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('idx_memory_items_expires'), table_name='memory_items', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('idx_memory_items_user_active'), table_name='memory_items')
    op.drop_constraint(op.f('memory_items_user_id_fkey'), 'memory_items', type_='foreignkey')
    op.create_foreign_key(None, 'memory_items', 'users', ['user_id'], ['id'])
    op.alter_column('metrics_rollup', 'day',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('metrics_rollup_user_id_fkey'), 'metrics_rollup', type_='foreignkey')
    op.create_foreign_key(None, 'metrics_rollup', 'users', ['user_id'], ['id'])
    op.alter_column('session_events', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_session_events_session_ts'), table_name='session_events')
    op.drop_constraint(op.f('session_events_session_id_fkey'), 'session_events', type_='foreignkey')
    op.create_foreign_key(None, 'session_events', 'sessions', ['session_id'], ['id'])
    op.alter_column('sessions', 'session_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index(op.f('idx_sessions_token'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_token'), 'sessions', ['session_token'], unique=False)
    op.alter_column('sessions', 'session_token',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'session_events', type_='foreignkey')
    op.create_foreign_key(op.f('session_events_session_id_fkey'), 'session_events', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_session_events_session_ts'), 'session_events', ['session_id', sa.literal_column('ts DESC')], unique=False)
    op.alter_column('session_events', 'type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'metrics_rollup', type_='foreignkey')
    op.create_foreign_key(op.f('metrics_rollup_user_id_fkey'), 'metrics_rollup', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('metrics_rollup', 'day',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'memory_items', type_='foreignkey')
    op.create_foreign_key(op.f('memory_items_user_id_fkey'), 'memory_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_memory_items_user_active'), 'memory_items', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_memory_items_expires'), 'memory_items', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.alter_column('memory_items', 'source',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('memory_items', 'kind',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'memory_feedback', type_='foreignkey')
    op.drop_constraint(None, 'memory_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('memory_feedback_user_id_fkey'), 'memory_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('memory_feedback_memory_item_id_fkey'), 'memory_feedback', 'memory_items', ['memory_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('memory_feedback', 'action',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_session_id_fkey'), 'chat_messages', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chat_messages_user_ts'), 'chat_messages', ['user_id', sa.literal_column('ts DESC')], unique=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_user_id_fkey'), 'audit_log', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('audit_log_session_id_fkey'), 'audit_log', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_audit_log_user_ts'), 'audit_log', ['user_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('idx_audit_log_session_ts'), 'audit_log', ['session_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('idx_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.alter_column('audit_log', 'severity',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'info'::text"))
    op.alter_column('audit_log', 'event_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'agent_suggestions', type_='foreignkey')
    op.create_foreign_key(op.f('agent_suggestions_user_id_fkey'), 'agent_suggestions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_agent_suggestions_user_ts'), 'agent_suggestions', ['user_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('idx_agent_suggestions_status'), 'agent_suggestions', ['status'], unique=False)
    op.alter_column('agent_suggestions', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'new'::text"))
    op.alter_column('agent_suggestions', 'type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.create_foreign_key(op.f('agent_actions_user_id_fkey'), 'agent_actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_agent_actions_user_ts'), 'agent_actions', ['user_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('idx_agent_actions_approval'), 'agent_actions', ['approval_status'], unique=False)
    op.alter_column('agent_actions', 'approval_status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('agent_actions', 'type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
